language: python
sudo: required
dist: bionic
services:
  - docker
before_install:
  - sudo ./container/install_tests.sh
python:
  - '3.7'

install:
  - pip install pipenv
  - make install-dev

script:
  # Build Docker images.
  - make docker-build-all

  # Run tests (using locally built Docker images).
  - make test-docker-compose
  # - make test-docker-compose-start && sleep 3 && make test-x && sleep 2 && make test-docker-compose-stop

# Publish images to Docker hub.
# Only in master branch commits.
# https://docs.travis-ci.com/user/docker/#pushing-a-docker-image-to-a-registry
# Could also be done in an after_success, see https://ops.tips/blog/travis-ci-push-docker-image/
deploy:
  provider: script
  script: bash container/docker_push.sh
  on:
    branch: master


env:
  global:
  - secure: UNIivM0GNNcdfwM2fo3QK2KzbUOvnvRieUDZg63HzqZ7KA7L8qQAAiyBqOXltGGSLnMsGKwafOeUv3+py/qe4yvHsMB+uDM0vEyA91TVAeRy0+6gDwiUT58IzKQLdjKzjCyQMd+QU7JwoWVJMVnvK60NUkUiQcVIRSaF1k65ge4sL3ZLuDIkL7Ssup0U0bYXFbj/RCCA3AoqvOA9Vr2ZZj2mTzbVj028nVUPtw+AhN/P1U0FfU6FAWlaLUkblRAr4pqh2WdyDBaBkqArwgh9M9QBM+9lk9tlNQf7Qiq9eEn+14TSZmWsV2c4Z2IIE2IEut2IhSrPhl5KkHDLAfnbxUmuUWnWTwZp0g0jOUvapQPmsiXsqDjHbEl1XuFzFuclKfr09R3mNkL9Jd/TF+xnKJLjJD4pQhv7OAwm1ue0Jj2EipA9hlQRSUSW9luIvPiH1at+KxDXUz2K4pMhrZPEmKRC7mzP+eQzRqJG6jUkig+wDoHr/rS/PPptmI46j8JlAGNW/Fsm37YZeJPNt6AmAgIBpfZgieR5Tc/EYM1UbJnJqhA9+9PXkRKloyrhTlN7O6F106qWMrmn4DNOAmiHnRAjApuaUVBmUjJHEapPONRjGyhk3Zs9esy9Lr6dg1+r8z5xl7PPUjFeMrRT9NJzfxrIIijTLJn9goBF1qFx0xU=
  - secure: mEJk4EweyUhpG+TbiBRw15lUcsd+bAjPtELJbv6WEUXrrIVh4OGM3KCv1glpGSxgCy9mMQMwRhqWJcWk/GX736FXWyXYpDRZCH+RAR8kGnB8o/atCI3LpABfWOKGHZtBZJk0VYiXqkN4xjARX6kUSVXbXiJ40HC6cGs3eQ+u31tPuHqLDog6m+83vvLRYCu5KcdNA5hvS+7J9PSXjwK+QtVUXE8yuTNae8ZNG+UPga+7EzT4Q/8yScMp8teZOqUQ2KnzvLCXsLjK3+aTfsdX7eD53oXg97sn+TZsCZdzibCh8MzLPO5fNylCHt+yVaE+a+H7Ry7udKZlqFSJmibF+OG2aAX+5jgA3ZFQFIvHB5l2CXvfHbkIfGqwmApcq3FgLJuyhukh7CjpMCpzvuaxf604P9Tf7mwAY/fHF1OmaxJA2XPlAOdbFLzfYTHDIWvoIFJwROfDyvrFzg9Tp+WfeZ6ApDFKcDgJUWmPKCOpZ0CO6eNOYdgfgcmAAka93bTuslrZEwNRskxVKv0s5n04ItDsL29ElPPPyf121//UAwOMUftiGH6LFwD4T+3df6ZAo/H2wJFK85F3P1hrZyY1nVKD0ax7I+pyFiBiW+FCwg3Y7KUc1lvudD+6qqhiG6V7IXukwWf+LPUF683drzG8Vwra8Oq9wtsdYMl63VbADfg=
