language: python
sudo: required
dist: trusty
services:
  - docker
before_install:
  - sudo ./container/install_tests.sh
    # - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended
    #   texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended
    # TODO Use a Docker pre-built image for running tests https://docs.travis-ci.com/user/docker/
    # This won't let us test different version of Python (although easily) but should
    # make the tests faster to run.
    # We may even pre-built the image in a stage, but if we do that each time it
    # won't be faster at all https://docs.travis-ci.com/user/build-stages/share-docker-image/
    # - sudo ./container/install_texlive.sh
    # - sudo ./container/install_latex_packages.sh
python:
    - '3.6'
install:
    - pip install pipenv
    - make install-dev
script:
    - make test-docker-compose
notifications:
  slack:
    rooms:
      secure: CpZNJiI/8E3QnZrcSU7bK8e7yJ538LNggc7iRocMVqgMxANeMUZxCQZx3BwxpU3Bz1H+fOto7BUIZfhA47EQGXQ5BUcJcxqnaMbaL5uARp7n8ffc6cYgGrBuuxtgc6CJaUi6HdHb9n2WLMkrO//cBX6anDI81zZ4cCi5rzcLoc1IlEsj3AJUrUrf7l5HAjv+LCw8IbtXpFxYIdoNGi21l+/PvYEVPRlSTDLVUuKTbRGkLxbByDZZAOFBcugHSwzu1WU9U1B0hVK6NkKTkVjQGMDQ2GxjOxzXeC8bPGAWZ15EfF1oMlwRhjWPGwoTmUmLEJl8JOAfE0PS78KwdmnxFv7wItXjcOhKKkdQkLy4c/g3TWjWVmtYQT8zdpAe9MJ0OJnXerUwinAMYH9QZAzwGLc+7ej1edYzY3Ud0un5xGel5uuvHrsxgW7/d4Q63qlkuFZHExnFxC3V6w2LUVA5TdFzRFDzvRZMMbyfYIP9rML7TvwwAyNp55KKu7O4rz/PLN6iS1cUXtdTxB/RxlwOWageonL4Kc/EBiUdwa3Mh7FDST2mUq9mb/z+2AXEinyzAAn9p48I5Q0UJizsleVZsw5P9Prq1SvomFFznb9T+7SnWjRDW7/qWUS3Sa4z4gED5mqIyRFV14P9BBOaynVdjgEpfii88ZGUHTmAeUod5No=
