version: '3'

services:
  latex:
    build: .
    restart: always
    command: make start
    ports:
     - "127.0.0.1:2345:8080"
    volumes:
     - .:/app/latex-on-http
    environment:
      CACHE_HOST: cache
  cache:
    build:
      context: .
      dockerfile: cache.Dockerfile
    restart: always
    command: make start-cache
    volumes:
     - .:/app/latex-on-http
