version: '3'

services:
  latex:
    build: .
    command: make debug
    ports:
     - "8080:8080"
    volumes:
     - .:/app/latex-on-http
    environment:
      CACHE_HOST: cache
  cache:
    build:
      context: .
      dockerfile: cache.Dockerfile
    command: make debug-cache
    volumes:
     - .:/app/latex-on-http
    restart: on-failure
