name: build-and-test
on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - master
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build-ant-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      # - name: Install tests
      #   run: ./container/install_tests.sh
      #   shell: bash
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          make install-dev
      - name: Build Docker images
        run: make docker-build-all
      - name: Run tests (using locally built Docker images)
        run: make test-docker-compose

# TODO Publish images to Docker hub.
# Only on tag or release
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release

# From Travis.yml:
# # Publish images to Docker hub.
# # Only in master branch commits.
# # https://docs.travis-ci.com/user/docker/#pushing-a-docker-image-to-a-registry
# # Could also be done in an after_success, see https://ops.tips/blog/travis-ci-push-docker-image/
# deploy:
#   provider: script
#   script: bash container/docker_push.sh
#   on:
#     branch: master
